jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go run main.go
      - run: |
          git add README.md
          git commit -m "$(date date "+%Y-%m-%d")"
          git push origin main
"on":
  schedule:
    - cron: 0 0 * * *
